name: itmbti
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
  get: ^4.6.1
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  crypto: ^3.0.1
  http: ^0.13.4
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/meetpeople.jpg
   - assets/working.jpg
   - assets/firstpage.jpg
   - assets/firstpage2.jpg
   - assets/firstpage3.jpg
   - assets/firstpage4.jpg
   - assets/firstpage5.jpg
   - assets/firstpage6.jpg
   - assets/firstpage7.jpg
   - assets/second1.jpg
   - assets/second2.jpg
   - assets/second3.jpg
   - assets/second4.jpg
   - assets/second5.jpg
   - assets/second6.jpg
   - assets/second7.jpg
   - assets/third1.jpg
   - assets/third2.jpg
   - assets/third3.jpg
   - assets/third4.jpg
   - assets/third5.jpg
   - assets/third6.jpg
   - assets/third7.jpg
   - assets/fourth1.jpg
   - assets/fourth2.jpg
   - assets/fourth3.jpg
   - assets/fourth4.jpg
   - assets/fourth5.jpg
   - assets/fourth6.jpg
   - assets/fourth7.jpg
   - assets/serverroom.png
   - assets/systemexcel.png
   - assets/baemin.png
   - assets/code.png
   - assets/CS.png
   - assets/cs2.png
   - assets/ds.png
   - assets/dogai.png

  fonts:
    # - family: TMoneyBold
    #   fonts:
    #     - asset: fonts/TmoneyRoundWindExtraBold.ttf  
    - family: TMoney
      fonts:
        - asset: fonts/TmoneyRoundWindExtraBold.ttf  